### ISSUE TITLE
No control over individual phase available power

### ISSUE THREAD

**Issue by kroeckx** [custom-components/zaptec#101]
If you go to the zaptec installation device, it shows under control:
- Available current

And under sensors:
- Available current phase 1
- Available current phase 2
- Available current phase 3

If you change the available current under control, all the ones under sensors change too.

The website allows you to control the available current per phase, and the values under sensors get updated in that case. I have a power meter, and so I would like to automate the available current based on used current per phase, but there doesn't seem to be a control for that now.

**Comment by sveinse** [comment]
Setting the 3 phase specific values can be done via the "zaptec.limit_current" service call. Unfortunately having 3 phase control sliders in HA doesn't work well with Zaptec, since they have to be updated together. See here https://github.com/sveinse/zaptec/issues/22#issuecomment-1751980133 for a longer reasoning.

**Comment by sveinse** [comment]
I'm closing the issue. Please reopen if there are any follow-up on this. Thanks.
