### ISSUE TITLE
Manually add automation to HA

### ISSUE THREAD

**Issue by hreuver0183** [custom-components/zaptec#107]
I tried to add the automation using HACS but it seems not present.
Is there a guide to install the add-on/automation manually from github?

**Comment by sveinse** [comment]
This integration is available in HACS as "Zaptec EV Charger".

**Comment by sveinse** [comment]
I'd be grateful if someone would make a writeup of how to install the Zaptec integration without using HACS. 👍

**Comment by Fysme** [comment]
I just installed the integration manually(I use Home Assistant in Docker so that is the only option for me). It was pretty straight forward.

1. Clone or download the repository to the server where you have Home Assistant installed.

2. Copy the downloaded folder zaptec under custom_components to the custom_components folder where Home Assistant is installed. If you have now custom_components folder then you have to create it.

3. Add the lines from the downloaded configuration.yaml to your Home Assistant installations configuration.yaml.

4. Restart Home Assistant

5. Finished!

Might be that this doesn't do everything that HACS do but seems to work for me.

**Comment by sveinse** [comment]
@Fysme I used the description you provided and updated the documentation. I changed it a bit:
* The component should be added to `config/custom_components/zaptec` in HA
* It's not necessary to add the `confiuration.yaml`. This was just for development purposes.
* Add the integration to HA in the same way as HACS
Thank you for providing the info!
