### ISSUE TITLE
Get power information from Zaptec Sense

### ISSUE THREAD

**Issue by baunan** [custom-components/zaptec#123]
Could be a dublicate of this request which is closed, https://github.com/custom-components/zaptec/issues/121

I have a Zaptec Sense installed and the information from the Sense unit generates this figure.
![image](https://github.com/user-attachments/assets/d62a6962-e40f-4524-abb2-a798608df42e)

I see from the portal that the request for info goes to the api
https://api.zaptec.com/api/installation/xxxxxxx-yyyy-dddd-cccc-ffffffff/energySensorData?from=2024-10-02T13:47:03.000Z&to=2024-10-04T13:57:25.716Z&resolution=day1
Payload: from=2024-10-03T08:44:49.000Z&to=2024-10-05T08:49:18.424Z&resolution=day1
From the request the following json formated information is provided see attachment.
[power-json.txt](https://github.com/user-attachments/files/17265603/power-json.txt)
For my part it would the power reading that is of interest to get a sensor value on so that I can track the total power consumption for the house, but there could be additional information here of interest.
Would it be possible to get this info?

**Comment by sveinse** [comment]
A couple of questions springs to mind:
- What specific entities (sensors) are you looking for? 
- What is the URL for the current data?
- How should these sensors be updates? I.e. how often should the Zaptec cloud be polled for energy data?

The second question is important. Please be advised that HA doesn't really handle historic data coming from other systems such as Zaptec. It's built on sampling data here and now and any history you see in HA is based on the gathered data. So I would assume that we would only be interested in the latest measurements.

PS! I do not have Zaptec sense, so it will be hard to develop anything for it, since I am unable to test anything.

**Comment by baunan** [comment]
As mentioned what I was after is the power reading, so that I can use the Sense unit as a HAN sensor. So in node-red I have made a sensor which just grab the last value in the array. As from the attachement the data is updates about every second minute, so that is how frequent I update that sensor. The URL is the api link (https://api.zaptec.com/api/installation/xxxxxxx-yyyy-dddd-cccc-ffffffff/energySensorData?from=2024-10-02T13:47:03.000Z&to=2024-10-04T13:57:25.716), please note that it is the installation ID that is used (so replace x-y-d-c-f with that) , but the api token is the same. In node-red I just pull the data from the last hour

**Comment by sveinse** [comment]
As far as my understanding of HA, it's not possible to do a request with the data from the last hour and inject this into the history. It can only store the instantaneous value at the time it has been sampled. So any data in HAs sensors will only have the resolution equal to the poll rate.

Other components, such as nordpool, reads the electricity price for the next 24 hours and stores the values as hourly attributes. The user must then use some custom templates to extract the information for display and graphing. That's also possible here, but it will create some work to make a display as above.

**Comment by baunan** [comment]
The graph will easy enough to make once you collect the data, so not sure why you are so focus on that. As per my initialt request, if you have the Sense install you also get access to the house total power consumption. That informtion could be of important for somebody as like myself as then I don't have to install a separate HAN sensor for that. So perhaps start by grabbing that information to HA? As saif before via Node-red I grab this information by requesting the last hour and just grab the last value in the array and send it to the HA sensor.

**Comment by sveinse** [comment]
How do you suggest the development of this should be done? Let's ask the obvious question: Are you able to make a PR with the code changes? Please be advised: I am unfortunately very busy at the moment, and I've got limited time to support and develop this and cannot reliably guarantee when I can look at it. Help wanted. Since I don't have Zaptec Sense (and I don't plan to since I have another HAN), I won't be able to test any of the things if I'm the one doing the implementation. It's a tedious way of doing development. 

Is the API for the Sense officially documented anywhere? I'd prefer using official APIs if possible, as reverse engineered ones tend to be changed or removed in time.

On the technical side, what happens if you call the API link without any additional parameters?https://api.zaptec.com/api/installation/xxxxxxx-yyyy-dddd-cccc-ffffffff/energySensorData What kind of response and data do you get?

I think the easiest would be to link this to the general Zaptec integration data poll rate that happens every 30 or 60 seconds. If that's too often, it probably would need a separate timer. I'm a little reluctant to make too much special logic into the integration, since this the HAN functionality is not the main intent for the zaptec integration.

**Comment by baunan** [comment]
I see, as per the API information for the Sense you should stay below 150 request per hour, so if you pull by every 30seconds you will go above. It is easy enough to get additional Sense data via the Node-red integration, so if somebody need help with that, then contact me. I will close the request with this.

**Comment by keviny86** [comment]
@baunan did you manage to get total power consumption for the house? If so, can you share your solution? Thanks!

**Comment by baunan** [comment]
Hi, 
I do it Node-red
This is how it look like.
![image](https://github.com/user-attachments/assets/1b4b218a-843e-42dc-a88b-ec8e3066536b)

Request is made every 5min in the injector

The send block looks like this 
```
msg.headers = {
    'content-type':'application/x-www-form-urlencoded'};

msg.payload = {
    'username': 'your email',
    'password': 'your password',
    'grant_type': 'password'
}
return msg
```
request like this
![image](https://github.com/user-attachments/assets/4178c6ef-8011-4251-89b7-55c69d65abd4)


Token like this
```
var d = new Date();
//var IDAG = d;
var IDAG = d.toISOString();
msg.nowdate = IDAG
//var y = new Date(new Date().setDate(new Date().getDate() - 1));
var y = new Date(new Date().setHours(new Date().getHours() - 1));

var yesterday = y.toISOString();
msg.yesterdaydate = yesterday

var token = msg.payload.access_token
//var token = 123
var token1 = 'Bearer ' + token
msg.headers = {
    'Authorization': token1,
    'Accept': 'text/plain'
}
return msg;
```

Power node:
https://api.zaptec.com/api/installation/your_installation_id/energySensorData?from={{{yesterdaydate}}}&to={{{nowdate}}}
![image](https://github.com/user-attachments/assets/1d5eff79-7326-4a4e-a0cb-e95588537b85)

And the last one to get the power reading
```
let pe = msg.payload.Readings;
let e = pe.map(x => x.Power);
msg.payload = e;
var my_array = e;
var last_element = e[e.length - 1];
msg.power = last_element;
return msg;
```
Then it just to send msg.power to a HA via the sensor node

**Comment by keviny86** [comment]
So by doing this api request you get real time house power consumption?

**Comment by baunan** [comment]
Yes, that is correct.

**Comment by keviny86** [comment]
It would be nice if we could get this into this component :)

**Comment by keviny86** [comment]
@baunan i don't have experience with node-red, could you export your flow and share it here?

**Comment by sveinse** [comment]
What happens if the URL is called without the `from=` and `to=` arguments? What does it return?

**Comment by baunan** [comment]
@sveinse It doesn't return anything when I try it.

**Comment by sveinse** [comment]
@baunan  ok thanks. So the API is dependent on a time range to return any data.

**Comment by ewels** [comment]
Many thanks for your post here @baunan - I followed your instructions and got it working, exactly what I was looking for! 🚀 

I have the instantaneous power usage in Home Assistant now, but I'm curious if anyone has managed to use this to set up energy usage in the HA Energy tab? So in other words, `kWh` instead of `kW`.

The Zaptec API seems to return this usage, so I think it should be possible:

<details><summary>Example response:</summary>

```
https://api.zaptec.com/api/installation/[MY-INSTALLATION-ID]/energySensorData?from=2024-12-01T22:30:04.645Z&to=2024-12-01T23:29:41.322Z
```

```json
{
  "ChargeEnergy": [
    {
      "IntervalStart": "2024-12-01T22:00:00Z",
      "Interval": "01:00:00",
      "Value": 0
    },
    {
      "IntervalStart": "2024-12-01T23:00:00Z",
      "Interval": "01:00:00",
      "Value": 0
    }
  ],
  "TotalEnergy": [
    {
      "IntervalStart": "2024-12-01T22:00:00Z",
      "Interval": "01:00:00",
      "Value": 0.9450830221442128
    },
    {
      "IntervalStart": "2024-12-01T23:00:00Z",
      "Interval": "01:00:00",
      "Value": 1.029224264226727
    }
  ],
  "Readings": [
    {
      "Timestamp": "2024-12-01T22:31:24.162954+00:00",
      "Power": 1.8025692542118141
    },
    {
      "Timestamp": "2024-12-01T22:40:24.142941+00:00",
      "Power": 1.7768587162637746
    },
    {
      "Timestamp": "2024-12-01T22:49:14.1853139+00:00",
      "Power": 0.9691328748057995
    },
    {
      "Timestamp": "2024-12-01T22:49:33.6132401+00:00",
      "Power": 0.8696953245685827
    },
    {
      "Timestamp": "2024-12-01T22:58:58.6659868+00:00",
      "Power": 0.8197336088002276
    },
    {
      "Timestamp": "2024-12-01T23:07:54.0411305+00:00",
      "Power": 0.7668881604463368
    },
    {
      "Timestamp": "2024-12-01T23:17:25.211568+00:00",
      "Power": 0.8808485696288871
    },
    {
      "Timestamp": "2024-12-01T23:26:25.2027521+00:00",
      "Power": 1.1999717652144997
    }
  ],
  "PowerLimit": 17.25,
  "LastReading": {
    "UniqueId": "xxx123456",
    "ObservedAt": "2024-12-01T23:26:00+00:00",
    "CurrentPhase1": 1.600000023841858,
    "CurrentPhase2": 3.2759268283844,
    "CurrentPhase3": 0.4000000059604645,
    "ChargeCurrentPhase1": 0,
    "ChargeCurrentPhase2": 0,
    "ChargeCurrentPhase3": 0,
    "AvailableCurrentPhase1": 18,
    "AvailableCurrentPhase2": 18,
    "AvailableCurrentPhase3": 18,
    "AvailableCurrentChanged": false,
    "CurrentNeutral": 0,
    "VoltagePhase1": 222.8980255126953,
    "VoltagePhase2": 228.73101806640625,
    "VoltagePhase3": 235.0720977783203,
    "StatusCode": "0000",
    "StatusMessage": "CYCL, #0 T#9m0s, 2.0, AMAX 25.0A, AVG 30, -85.0dBm, 82%, 0, FC:0 0 0, HB:195436, HD:118144, UT1733095571, S204, 6.0.0.2, fac ",
    "Ripple": 0,
    "PartitionKey": "xxx123456_1",
    "RowKey": "1234567891234567",
    "Timestamp": "2024-12-01T23:26:25.2027521+00:00"
  },
  "Interval": {
    "From": "2024-12-01T22:30:04.645Z",
    "To": "2024-12-01T23:29:41.322Z",
    "Duration": "00:59:36.6770000"
  }
}
```

</details>

I extended the JS snippet to also get the most recent `TotalEnergy`:

```js
// Current power
let pe = msg.payload.Readings;
let e = pe.map(x => x.Power);
var my_array = e;
var last_element = e[e.length - 1];
msg.power = last_element*1000.0;

// Energy usage in last period
let te = msg.payload.TotalEnergy;
let tee = te.map(x => x.Value);
var last_energy = tee[tee.length - 1];
msg.energy = last_energy*1000.0;

// Return
msg.payload = e;
return msg;
```

That worked, but I think that I need something more to do with time period / reset time maybe? I got a warning in the Energy panel about not having a reset. I added the current time to see what'd happen and I got a single reading, but nothing after that.

Has anyone else figured this out already?
