### ISSUE TITLE
Exceed maximum size of 16384 bytes

### ISSUE THREAD

**Issue by Howard0000** [custom-components/zaptec#88]
Hei

I get this.
<img width="459" alt="2024-01-13 115843" src="https://github.com/custom-components/zaptec/assets/146569636/942195a6-45a2-4024-b8fb-7a52ca1ee185">

**Comment by sveinse** [comment]
This happens because all parameters from zaptec cloud are added to the attributes of this entity. This was the way the version <0.7 of zaptec integration stored the data. I think the reason you get this is that the dataset is getting too big.

We might need to remove some parameter to ensure we get below the 16k limit. Do you have any attributes in that entity that are particularly big or long?

**Comment by Howard0000** [comment]
Hi

Production test results and Completed session are long.

**Comment by sveinse** [comment]
@Howard0000 what is the precise name for the attribute that contains the "Production test results"? To be able to filter it away, I need to 

It would be nice if you could share a diagnostics file. Settings -> Devices and Services -> Devices -> <Select your charger> -> Press DOWNLOAD DIAGNOSTCS which is found under "Device info". The file is anonymized and should not contain any personal data (but bugs might exists, so please double check).

**Comment by Howard0000** [comment]
Hi

Here is the file.
[zaptec-37ecb7a907630dacb6f2d2074d16f951-P-plass 72-7d7b551095771d049314c850ade9becd.json](https://github.com/user-attachments/files/17071244/zaptec-37ecb7a907630dacb6f2d2074d16f951-P-plass.72-7d7b551095771d049314c850ade9becd.json)

**Comment by sveinse** [comment]
Thank you @Howard0000, there were indeed very large attributes in the dataset from your charger. This helped me make a fix for filtering them out. 👌

**Comment by sveinse** [comment]
A fix for the issue have been pushed to master. Please install the "master" version and test if this fixes the observed problems. @Howard0000
